### ISSUE TITLE
confusing warning message

### ISSUE THREAD

**Issue by jiazhengshi** [magento/m2-baler#2]
Overall, this is a good M2 extension.  It could be more helpful, if the author can clarify the system warning message. 
[Be sure that you have your theme bundles config](https://github.com/magento/m2-baler/blob/master/etc/adminhtml/system.xml#L16)

**Comment by adifucan** [comment]
Thanks @jiazhengshi for the issue. Fixed in https://github.com/magento/m2-baler/commit/5a7a0d0e43f590d41ac1b1410e7d86eee2b9bd60
